return {
  { "akinsho/toggleterm.nvim" },
  { "catppuccin/nvim" },
  { "doums/darcula" },
  { "folke/tokyonight.nvim" },
  { "lewis6991/gitsigns.nvim" },
  { "mhinz/vim-startify" },
  { "nvim-tree/nvim-web-devicons" },
  { "rhysd/git-messenger.vim" },
  { "tpope/vim-fugitive" },
  { "yardnsm/vim-import-cost" },
  -- require("plugins.chat-gpt"),
  require("plugins.conform"),
  require("plugins.blankline"),
  require("plugins.bufferline"),
  require("plugins.formatting"),
  require("plugins.git-blame"),
  require("plugins.jest"),
  require("plugins.lazygit"),
  require("plugins.lspsaga"),
  require("plugins.lualine"),
  require("plugins.mason"),
  -- require("plugins.neotree"),
  require("plugins.nvim-autopairs"),
  require("plugins.nvim-cmp"),
  require("plugins.nvim-comment"),
  -- require("plugins.nvim-lint"),
  require("plugins.nvim-lspconfig"),
  require("plugins.nvim-scrollbar"),
  require("plugins.nvim-surround"),
  require("plugins.nvim-tree"),
  require("plugins.nvim-treesitter"),
  require("plugins.nvim-ts-autotag"),
  require("plugins.scope"),
  require("plugins.telescope"),
  require("plugins.trouble"),
}
